### ISSUE TITLE
Maximum recursion depth error

### ISSUE THREAD

**Issue by michnov** [ufal/UMRGraphViz#8]
Processing of the first sentence in https://github.com/ufal/UMR/blob/main/data/latin/DeConCat_par1.txt fails with:

```
2024-01-08 13:43:58,899: INFO: processing issue_latin.txt
Traceback (most recent call last):
  File "/lnet/troja/work/people/mnovak/umr/amr-reader/amrreader/src/reader.py", line 280, in retrieve_path
    retrieve_path(i, node.name, path)
  File "/lnet/troja/work/people/mnovak/umr/amr-reader/amrreader/src/reader.py", line 280, in retrieve_path
    retrieve_path(i, node.name, path)
  File "/lnet/troja/work/people/mnovak/umr/amr-reader/amrreader/src/reader.py", line 280, in retrieve_path
    retrieve_path(i, node.name, path)
  [Previous line repeated 997 more times]
RecursionError: maximum recursion depth exceeded

```

**Comment by michnov** [comment]
The error was in the datafile. Fixed by:
https://github.com/ufal/UMR/commit/91ea399b990becef919307b7abe2fe44ddf1ec31
https://github.com/ufal/UMR/commit/1523614ff32cfd994947ed52514f6c5c629b1d0c
